# Generated by Django 3.2 on 2023-10-11 15:06

from django.db import migrations, models
import recipies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[recipies.validators.validate_cooking_time], verbose_name='Время приготовления рецепта'),
        ),
    ]
