# Generated by Django 3.2 on 2023-10-30 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0004_auto_20231025_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_in_recipe', to='recipies.ingredient', verbose_name='Ингредиент'),
        ),
    ]
