# Generated by Django 3.2 on 2023-11-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_auto_20231031_1042'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingridientinrecipe',
            name='recipe_ingredient',
        ),
        migrations.AlterField(
            model_name='ingridientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingridientinrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipies.recipe', verbose_name='Рецепт'),
        ),
        migrations.AddConstraint(
            model_name='ingridientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='ingredient_in_recipe'),
        ),
    ]
